export const dummyTasks = [
  {
    title: "Finish math assignment",
    description: "Complete calculus worksheet 5 before deadline",
    priority: "High",
    status: "pending",
    category: "Education",
  },
  {
    title: "Submit college fees",
    description: "Last date is 10th April, check portal",
    priority: "High",
    status: "pending",
    category: "Finance",
  },
  {
    title: "Read chapter 4 of Physics",
    description: "Focus on Newton's laws and examples",
    priority: "Medium",
    status: "pending",
    category: "Education",
  },
  {
    title: "Join online class for Data Structures",
    description: "Live class at 5 PM on Zoom",
    priority: "Medium",
    status: "completed",
    category: "Education",
  },
  {
    title: "Download college timetable",
    description: "Get new semester schedule from student portal",
    priority: "Low",
    status: "completed",
    category: "Education",
  },
  {
    title: "Clean study table",
    description: "Organize books, files, and remove clutter",
    priority: "Low",
    status: "completed",
    category: "Chores",
  },
  {
    title: "Pay hostel rent",
    description: "GPay or cash before 7th",
    priority: "Medium",
    status: "pending",
    category: "Finance",
  },
  {
    title: "Prepare for group presentation",
    description: "Slides and script for Environmental Studies topic",
    priority: "High",
    status: "pending",
    category: "Education",
  },
  {
    title: "Workout for 30 mins",
    description: "Try beginner HIIT or yoga video",
    priority: "Low",
    status: "completed",
    category: "Health",
  },
  {
    title: "Attend coding club meet",
    description: "Monthly discussion on open-source contributions",
    priority: "Medium",
    status: "completed",
    category: "Meetings",
  },
  {
    title: "Plan trip for semester break",
    description: "Check travel options with friends",
    priority: "Low",
    status: "pending",
    category: "Travel",
  },
  {
    title: "Buy stationery",
    description: "Pens, highlighters, sticky notes",
    priority: "Low",
    status: "completed",
    category: "Shopping",
  },
  {
    title: "Watch Python tutorial",
    description: "Basics of OOP from freeCodeCamp",
    priority: "Medium",
    status: "pending",
    category: "Education",
  },
  {
    title: "Talk to academic counselor",
    description: "Book a session for subject selection",
    priority: "High",
    status: "pending",
    category: "Personal",
  },
  {
    title: "Take backup of notes",
    description: "Upload all PDF notes to Google Drive",
    priority: "Medium",
    status: "completed",
    category: "Work",
  },
  {
    title: "Call home",
    description: "Catch up with parents and siblings",
    priority: "Low",
    status: "completed",
    category: "Personal",
  },
  {
    title: "Finish capstone project draft",
    description: "Add features and write documentation",
    priority: "High",
    status: "pending",
    category: "Work",
  },
  {
    title: "Eat more fruits",
    description: "Buy bananas and apples",
    priority: "Low",
    status: "pending",
    category: "Health",
  },
  {
    title: "Practice aptitude problems",
    description: "Prep for placement test",
    priority: "High",
    status: "pending",
    category: "Education",
  },
  {
    title: "Meet project partner",
    description: "Discuss modules and deadlines",
    priority: "Medium",
    status: "completed",
    category: "Meetings",
  },
  {
    title: "Watch documentary for assignment",
    description: "The Social Dilemma for media studies",
    priority: "Medium",
    status: "completed",
    category: "Education",
  },
  {
    title: "Apply for internship",
    description: "Check internshala and LinkedIn",
    priority: "High",
    status: "pending",
    category: "Work",
  },
  {
    title: "Meditate for 10 minutes",
    description: "Use Headspace app",
    priority: "Low",
    status: "pending",
    category: "Health",
  },
  {
    title: "Organize laptop folders",
    description: "Separate personal and academic files",
    priority: "Low",
    status: "completed",
    category: "Chores",
  },
  {
    title: "Write daily journal",
    description: "Reflect on today’s learnings and mood",
    priority: "Low",
    status: "pending",
    category: "Personal",
  },
  {
    title: "Check scholarship result",
    description: "Login to official portal on 12th",
    priority: "High",
    status: "pending",
    category: "Finance",
  },
  {
    title: "Rewatch economics lecture",
    description: "Macro module was confusing",
    priority: "Medium",
    status: "pending",
    category: "Education",
  },
  {
    title: "Fix broken headphone",
    description: "Try resetting or claim warranty",
    priority: "Low",
    status: "pending",
    category: "Others",
  },
  {
    title: "Collect lab coat from laundry",
    description: "Needed for chemistry practical",
    priority: "Medium",
    status: "pending",
    category: "Chores",
  },
  {
    title: "Prepare for mock interview",
    description: "Technical + HR round practice",
    priority: "High",
    status: "pending",
    category: "Work",
  },
];
